name: Daily Scribd Upload

on:
  schedule:
    - cron: "30 3 * * *"  # runs once per day at midnight UTC
  workflow_dispatch:     # allows manual trigger

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      SCRIBD_SESSION: ${{ secrets.SCRIBD_SESSION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run upload script
        run: |
          python3 main.py
