name: Daily Scribd Upload

on:
  schedule:
    - cron: "0 3 * * *"  # every day at midnight UTC
  workflow_dispatch:      # allows manual trigger via Actions tab

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      SCRIBD_SESSION: ${{ secrets.SCRIBD_SESSION }}
      CAPTCHA_KEY: ${{ secrets.CAPTCHA_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: gcloud login
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run upload script
        run: |
          python3 main.py
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'

      - name: upload to my gcloud
        run: |
          gcloud storage cp *.pdf gs://noble-might-330612.appspot.com/news-archive/$(date +'%Y-%m-%d')/
