name: Daily Scribd Upload

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      SCRIBD_SESSION: ${{ secrets.SCRIBD_SESSION }}
      CAPTCHA_KEY: ${{ secrets.CAPTCHA_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # - name: gcloud login
      #   uses: 'google-github-actions/auth@v3'
      #   with:
      #     credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run upload script
        run: |
          python3 main.py
      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v3'
      #   with:
      #     version: '>= 363.0.0'

      # - name: upload to my gcloud
      #   run: |
      #     gcloud storage cp *.pdf gs://noble-might-330612.appspot.com/news-archive/$(date +'%Y-%m-%d')/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this to your bucket's region

      - name: Upload pdfs to S3 glacier archive
        run: |
          DATE_DIR=$(date +'%Y-%m-%d')
          mkdir -p "$DATE_DIR"
          mv *.pdf "$DATE_DIR/"
          aws s3 cp "$DATE_DIR" s3://***/news-archive/ --recursive --storage-class DEEP_ARCHIVE
